// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIsgUEtDM470nPAg0DN3IM-_ne3Ax6irg',
    appId: '1:319989980707:web:bfaf27f6bc91cc2be1db96',
    messagingSenderId: '319989980707',
    projectId: 'flaura-g3',
    authDomain: 'flaura-g3.firebaseapp.com',
    databaseURL: 'https://flaura-g3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flaura-g3.firebasestorage.app',
    measurementId: 'G-6CS650PWZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmvuT3KwuxxECNdPSUQS-MYGXBFstnRN4',
    appId: '1:319989980707:android:6234e9e312a4ef74e1db96',
    messagingSenderId: '319989980707',
    projectId: 'flaura-g3',
    databaseURL: 'https://flaura-g3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flaura-g3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrw0EQLoNOPy_S7vcMFCMtv0twQ1YCG6A',
    appId: '1:319989980707:ios:73e50d282e687a83e1db96',
    messagingSenderId: '319989980707',
    projectId: 'flaura-g3',
    databaseURL: 'https://flaura-g3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flaura-g3.firebasestorage.app',
    iosClientId: '319989980707-pnun3k2uhbjb034il918aosesjdrqejc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flauraapp',
  );
}
